# Generated by Django 3.2.3 on 2021-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodesGeo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(blank=True, max_length=5, null=True)),
                ('suburb', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=4, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'postcodes_geo',
                'managed': False,
            },
        ),
    ]
